# Generated by Django 4.2.9 on 2024-01-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.CharField(max_length=20),
        ),
    ]
