# Generated by Django 4.2.9 on 2024-01-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating_count',
            field=models.CharField(max_length=25),
        ),
    ]
