# Generated by Django 4.2.9 on 2024-01-30 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_product_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
